const quotes = [
  { "quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs" },
  { "quote": "Innovation distinguishes between a leader and a follower.", "author": "Steve Jobs" },
  { "quote": "Stay hungry, stay foolish.", "author": "Steve Jobs" },
  { "quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "author": "Winston Churchill" },
  { "quote": "The pessimistic complains about the wind; the optimist expects it to change; the realist adjusts the sails.", "author": "William Arthur Ward" },
  { "quote": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
  { "quote": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt" },
  { "quote": "The only thing we have to fear is fear itself.", "author": "Franklin D. Roosevelt" },
  { "quote": "In the middle of every difficulty lies opportunity.", "author": "Albert Einstein" },
  { "quote": "Imagination is more important than knowledge.", "author": "Albert Einstein" },
  { "quote": "Try not to become a man of success, but rather try to become a man of value.", "author": "Albert Einstein" },
  { "quote": "Education is the most powerful weapon which you can use to change the world.", "author": "Nelson Mandela" },
  { "quote": "It always seems impossible until it's done.", "author": "Nelson Mandela" },
  { "quote": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
  { "quote": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi" },
  { "quote": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi" },
  { "quote": "Happiness is when what you think, what you say, and what you do are in harmony.", "author": "Mahatma Gandhi" },
  { "quote": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa" },
  { "quote": "If you judge people, you have no time to love them.", "author": "Mother Teresa" },
  { "quote": "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", "author": "Martin Luther King Jr." },
  { "quote": "The time is always right to do what is right.", "author": "Martin Luther King Jr." },
  { "quote": "I have a dream.", "author": "Martin Luther King Jr." },
  { "quote": "Well done is better than well said.", "author": "Benjamin Franklin" },
  { "quote": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "author": "Benjamin Franklin" },
  { "quote": "An investment in knowledge pays the best interest.", "author": "Benjamin Franklin" },
  { "quote": "The best way to predict the future is to invent it.", "author": "Alan Kay" },
  { "quote": "Whether you think you can or you think you can't, you're right.", "author": "Henry Ford" },
  { "quote": "Coming together is a beginning; keeping together is progress; working together is success.", "author": "Henry Ford" },
  { "quote": "Don't find fault, find a remedy.", "author": "Henry Ford" },
  { "quote": "Everything has beauty, but not everyone sees it.", "author": "Confucius" },
  { "quote": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius" },
  { "quote": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "author": "Ralph Waldo Emerson" },
  { "quote": "Life is a journey, not a destination.", "author": "Ralph Waldo Emerson" },
  { "quote": "The only way to have a friend is to be one.", "author": "Ralph Waldo Emerson" },
  { "quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde" },
  { "quote": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde" },
  { "quote": "I can resist everything except temptation.", "author": "Oscar Wilde" },
  { "quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West" },
  { "quote": "Go confidently in the direction of your dreams. Live the life you have imagined.", "author": "Henry David Thoreau" },
  { "quote": "Things do not change; we change.", "author": "Henry David Thoreau" },
  { "quote": "Not all those who wander are lost.", "author": "J.R.R. Tolkien" },
  { "quote": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu" },
  { "quote": "Knowing others is intelligence; knowing yourself is true wisdom.", "author": "Lao Tzu" },
  { "quote": "Silence is a source of great strength.", "author": "Lao Tzu" },
  { "quote": "A room without books is like a body without a soul.", "author": "Marcus Tullius Cicero" },
  { "quote": "If you have a garden and a library, you have everything you need.", "author": "Marcus Tullius Cicero" },
  { "quote": "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", "author": "Dr. Seuss" },
  { "quote": "Why fit in when you were born to stand out?", "author": "Dr. Seuss" },
  { "quote": "Don't cry because it's over, smile because it happened.", "author": "Dr. Seuss" },
  { "quote": "You miss 100% of the shots you don't take.", "author": "Wayne Gretzky" },
  { "quote": "I’ve failed over and over and over again in my life and that is why I succeed.", "author": "Michael Jordan" },
  { "quote": "Talent wins games, but teamwork and intelligence win championships.", "author": "Michael Jordan" },
  { "quote": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi" },
  { "quote": "Winning isn't everything, but wanting to win is.", "author": "Vince Lombardi" },
  { "quote": "The best revenge is massive success.", "author": "Frank Sinatra" },
  { "quote": "I would rather die on my feet than live on my knees.", "author": "Emiliano Zapata" },
  { "quote": "The only true wisdom is in knowing you know nothing.", "author": "Socrates" },
  { "quote": "An unexamined life is not worth living.", "author": "Socrates" },
  { "quote": "Be kind, for everyone you meet is fighting a hard battle.", "author": "Plato" },
  { "quote": "Courage is knowing what not to fear.", "author": "Plato" },
  { "quote": "Quality is not an act, it is a habit.", "author": "Aristotle" },
  { "quote": "We are what we repeatedly do.", "author": "Aristotle" },
  { "quote": "Pleasure in the job puts perfection in the work.", "author": "Aristotle" },
  { "quote": "Life is what happens when you're making other plans.", "author": "John Lennon" },
  { "quote": "Imagination is the beginning of creation.", "author": "George Bernard Shaw" },
  { "quote": "Life isn't about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw" },
  { "quote": "If you want to live a happy life, tie it to a goal, not to people or things.", "author": "Albert Einstein" },
  { "quote": "The mind is everything. What you think you become.", "author": "Buddha" },
  { "quote": "Peace comes from within. Do not seek it without.", "author": "Buddha" },
  { "quote": "Three things cannot be long hidden: the sun, the moon, and the truth.", "author": "Buddha" },
  { "quote": "Dream as if you'll live forever, live as if you'll die today.", "author": "James Dean" },
  { "quote": "The purpose of our lives is to be happy.", "author": "Dalai Lama" },
  { "quote": "Be kind whenever possible. It is always possible.", "author": "Dalai Lama" },
  { "quote": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama" },
  { "quote": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill" },
  { "quote": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
  { "quote": "All our dreams can come true, if we have the courage to pursue them.", "author": "Walt Disney" },
  { "quote": "If you can dream it, you can do it.", "author": "Walt Disney" },
  { "quote": "Genius is one percent inspiration and ninety-nine percent perspiration.", "author": "Thomas Edison" },
  { "quote": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas Edison" },
  { "quote": "To be a great champion, you must believe you are the best. If you’re not, pretend you are.", "author": "Muhammad Ali" },
  { "quote": "Don't count the days, make the days count.", "author": "Muhammad Ali" },
  { "quote": "Float like a butterfly, sting like a bee.", "author": "Muhammad Ali" },
  { "quote": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman" },
  { "quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
  { "quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
  { "quote": "No one can make you feel inferior without your consent.", "author": "Eleanor Roosevelt" },
  { "quote": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt" },
  { "quote": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi" },
  { "quote": "The only limit to our realization of tomorrow will be our doubts of today.", "author": "Franklin D. Roosevelt" },
  { "quote": "Act as if what you do makes a difference. It does.", "author": "William James" },
  { "quote": "The greatest weapon against stress is our ability to choose one thought over another.", "author": "William James" },
  { "quote": "Life is 10% what happens to me and 90% of how I react to it.", "author": "Charles Swindoll" },
  { "quote": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs" },
  { "quote": "Everything you've ever wanted is on the other side of fear.", "author": "George Addair" },
  { "quote": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis" },
  { "quote": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis" },
  { "quote": "I am not a product of my circumstances. I am a product of my decisions.", "author": "Stephen Covey" },
  { "quote": "The two most important days in your life are the day you are born and the day you find out why.", "author": "Mark Twain" },
  { "quote": "Continuous improvement is better than delayed perfection.", "author": "Mark Twain" },
  { "quote": "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", "author": "Mark Twain" },
  { "quote": "It is never too late to be what you might have been.", "author": "George Eliot" },
  { "quote": "What you do speaks so loudly that I cannot hear what you say.", "author": "Ralph Waldo Emerson" },
  { "quote": "I didn't fail the test, I just found 100 ways to do it wrong.", "author": "Benjamin Franklin" },
  { "quote": "If you look at what you have in life, you'll always have more.", "author": "Oprah Winfrey" },
  { "quote": "The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work.", "author": "Oprah Winfrey" },
  { "quote": "Success is getting what you want. Happiness is wanting what you get.", "author": "Dale Carnegie" },
  { "quote": "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", "author": "Dale Carnegie" },
  { "quote": "You can't use up creativity. The more you use, the more you have.", "author": "Maya Angelou" },
  { "quote": "I've learned that people will forget what you said, but people will never forget how you made them feel.", "author": "Maya Angelou" },
  { "quote": "Nothing will work unless you do.", "author": "Maya Angelou" },
  { "quote": "If you cannot do great things, do small things in a great way.", "author": "Napoleon Hill" },
  { "quote": "Don't wait. The time will never be just right.", "author": "Napoleon Hill" },
  { "quote": "Whatever the mind can conceive and believe, it can achieve.", "author": "Napoleon Hill" },
  { "quote": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
  { "quote": "The man who has no imagination has no wings.", "author": "Muhammad Ali" },
  { "quote": "Our life is what our thoughts make it.", "author": "Marcus Aurelius" },
  { "quote": "Very little is needed to make a happy life; it is all within yourself.", "author": "Marcus Aurelius" },
  { "quote": "Waste no more time arguing about what a good man should be. Be one.", "author": "Marcus Aurelius" },
  { "quote": "The best revenge is to be unlike him who performed the injury.", "author": "Marcus Aurelius" },
  { "quote": "I destroy my enemies when I make them my friends.", "author": "Abraham Lincoln" },
  { "quote": "In the end, it's not the years in your life that count. It's the life in your years.", "author": "Abraham Lincoln" },
  { "quote": "Whatever you are, be a good one.", "author": "Abraham Lincoln" },
  { "quote": "Great minds discuss ideas; average minds discuss events; small minds discuss people.", "author": "Eleanor Roosevelt" },
  { "quote": "Doubt kills more dreams than failure ever will.", "author": "Suzy Kassem" },
  { "quote": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale" },
  { "quote": "Aim for the moon. If you miss, you may hit a star.", "author": "W. Clement Stone" },
  { "quote": "The power of imagination makes us infinite.", "author": "John Muir" },
  { "quote": "To be the best, you must be able to handle the worst.", "author": "Wilson Kanadi" },
  { "quote": "The secret of getting ahead is getting started.", "author": "Mark Twain" },
  { "quote": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar" },
  { "quote": "Small deeds done are better than great deeds planned.", "author": "Peter Marshall" },
  { "quote": "Action is the foundational key to all success.", "author": "Pablo Picasso" },
  { "quote": "Everything you can imagine is real.", "author": "Pablo Picasso" },
  { "quote": "I am always doing that which I cannot do, in order that I may learn how to do it.", "author": "Pablo Picasso" },
  { "quote": "If you're going through hell, keep going.", "author": "Winston Churchill" },
  { "quote": "Never, never, never give up.", "author": "Winston Churchill" },
  { "quote": "A goal is a dream with a deadline.", "author": "Napoleon Hill" },
  { "quote": "Excellence is not a skill. It is an attitude.", "author": "Ralph Marston" },
  { "quote": "Don't let yesterday take up too much of today.", "author": "Will Rogers" },
  { "quote": "If you want to fly, give up everything that weighs you down.", "author": "Toni Morrison" },
  { "quote": "Leadership and learning are indispensable to each other.", "author": "John F. Kennedy" },
  { "quote": "Ask not what your country can do for you – ask what you can do for your country.", "author": "John F. Kennedy" },
  { "quote": "Forgive your enemies, but never forget their names.", "author": "John F. Kennedy" },
  { "quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein" },
  { "quote": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein" },
  { "quote": "Creativity is intelligence having fun.", "author": "Albert Einstein" },
  { "quote": "The only thing that interferes with my learning is my education.", "author": "Albert Einstein" },
  { "quote": "Logic will get you from A to B. Imagination will take you everywhere.", "author": "Albert Einstein" },
  { "quote": "Do not pray for an easy life, pray for the strength to endure a difficult one.", "author": "Bruce Lee" },
  { "quote": "Mistakes are always forgivable, if one has the courage to admit them.", "author": "Bruce Lee" },
  { "quote": "Be water, my friend.", "author": "Bruce Lee" },
  { "quote": "The key to immortality is first living a life worth remembering.", "author": "Bruce Lee" },
  { "quote": "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", "author": "Bruce Lee" },
  { "quote": "Knowledge will give you power, but character respect.", "author": "Bruce Lee" },
  { "quote": "It’s not the daily increase but daily decrease. Hack away at the unessential.", "author": "Bruce Lee" },
  { "quote": "Simplicity is the key to brilliance.", "author": "Bruce Lee" },
  { "quote": "Simplicity is the ultimate sophistication.", "author": "Leonardo da Vinci" },
  { "quote": "Learning never exhausts the mind.", "author": "Leonardo da Vinci" },
  { "quote": "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigor of the mind.", "author": "Leonardo da Vinci" },
  { "quote": "Knowing is not enough; we must apply. Willing is not enough; we must do.", "author": "Johann Wolfgang von Goethe" },
  { "quote": "Magic is believing in yourself, if you can do that, you can make anything happen.", "author": "Johann Wolfgang von Goethe" },
  { "quote": "Turn your wounds into wisdom.", "author": "Oprah Winfrey" },
  { "quote": "Where there is no struggle, there is no strength.", "author": "Oprah Winfrey" },
  { "quote": "The standard you walk past is the standard you accept.", "author": "David Hurley" },
  { "quote": "If you want something you've never had, you must be willing to do something you've never done.", "author": "Thomas Jefferson" },
  { "quote": "The harder I work, the luckier I get.", "author": "Thomas Jefferson" },
  { "quote": "Honesty is the first chapter in the book of wisdom.", "author": "Thomas Jefferson" },
  { "quote": "The point of living is to believe the best is yet to come.", "author": "Peter Ustinov" },
  { "quote": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller" },
  { "quote": "The secret to success is to do the common thing uncommonly well.", "author": "John D. Rockefeller" },
  { "quote": "Success comes from curiosity, concentration, perseverance and self-criticism.", "author": "Albert Einstein" },
  { "quote": "The successful warrior is the average man, with laser-like focus.", "author": "Bruce Lee" },
  { "quote": "Keep your eyes on the stars, and your feet on the ground.", "author": "Theodore Roosevelt" },
  { "quote": "It is hard to fail, but it is worse never to have tried to succeed.", "author": "Theodore Roosevelt" },
  { "quote": "The only man who never makes a mistake is the man who never does anything.", "author": "Theodore Roosevelt" },
  { "quote": "Believe in yourself. You are braver than you think, more talented than you know.", "author": "Roy T. Bennett" },
  { "quote": "The best is yet to be.", "author": "Robert Browning" },
  { "quote": "Courage is grace under pressure.", "author": "Ernest Hemingway" },
  { "quote": "The world breaks everyone, and afterward, some are strong at the broken places.", "author": "Ernest Hemingway" },
  { "quote": "There is no friend as loyal as a book.", "author": "Ernest Hemingway" },
  { "quote": "The first wealth is health.", "author": "Ralph Waldo Emerson" },
  { "quote": "Life is short, and it is up to you to make it sweet.", "author": "Sarah Louise Delany" },
  { "quote": "Happiness is a warm puppy.", "author": "Charles M. Schulz" },
  { "quote": "The road to success is always under construction.", "author": "Lily Tomlin" },
  { "quote": "The best way out is always through.", "author": "Robert Frost" },
  { "quote": "I can sum up everything I've learned about life in three words: it goes on.", "author": "Robert Frost" },
  { "quote": "Two roads diverged in a wood, and I—I took the one less traveled by.", "author": "Robert Frost" },
  { "quote": "Love the life you live. Live the life you love.", "author": "Bob Marley" },
  { "quote": "The greatness of a man is not in how much wealth he acquires, but in his integrity and his ability to affect those around him positively.", "author": "Bob Marley" },
  { "quote": "One good thing about music, when it hits you, you feel no pain.", "author": "Bob Marley" },
  { "quote": "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", "author": "Bob Marley" },
  { "quote": "Emancipate yourselves from mental slavery. None but ourselves can free our minds.", "author": "Bob Marley" },
  { "quote": "You can fool some people sometimes, but you can't fool all the people all the time.", "author": "Bob Marley" },
  { "quote": "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", "author": "Bill Keane" },
  { "quote": "Do not let what you cannot do interfere with what you can do.", "author": "John Wooden" },
  { "quote": "It's the little details that are vital. Little things make big things happen.", "author": "John Wooden" },
  { "quote": "Failure is not fatal, but failure to change might be.", "author": "John Wooden" },
  { "quote": "Make each day your masterpiece.", "author": "John Wooden" },
  { "quote": "Discipline is the bridge between goals and accomplishment.", "author": "Jim Rohn" },
  { "quote": "Either you run the day or the day runs you.", "author": "Jim Rohn" },
  { "quote": "Success is nothing more than a few simple disciplines, practiced every day.", "author": "Jim Rohn" },
  { "quote": "The more you like yourself, the less you are like anyone else, which makes you unique.", "author": "Walt Disney" },
  { "quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
  { "quote": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost" }
]

export default quotes;
